version: '3'

services:
  db:
    container_name: rss_db
    build:
      dockerfile: dockerfiles/Dockerfile.db
      context: .

    ports:
    - 3306:3306

    environment:
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_USER=root

  app:
    container_name: rss_pp
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .

    environment:
      - DB_NAME=rss
      - DB_HOST=db
      - DB_PORT=3306
      - DB_PASSWORD=test
      - DB_USER=root

    ports:
      - 8000:8000

    depends_on:
      - db
